Language: en #Languages can be found on lang directory
CommandCooldown: 1 #Time by seconds
GuildCreate:
  RequirePermission: false
  Permission: guild.create
  Message: "&c✖ You don't have permission for this."
  MinimumNameLength: 3
  MaximumNameLength: 16
GuildTag:
  MinimumTagLength: 2
  MaximumTagLength: 3
BlockedGuildNames:
  - some
  - blocked
  - names
BlockedGuildTags:
  - some
  - blocked
  - tags


